services:
  vote:
    build:
      context: .
      dockerfile: docker/vote.Dockerfile
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    ports:
      - "5432:5432"

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    depends_on:
      - redis
      - postgres

  result:
    build:
      context: .
      dockerfile: docker/result.Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - postgres